### ISSUE TITLE
Unknown place where the editor is installing

### ISSUE THREAD

**Issue by AlexMorgan3817** [SpaiR/sdmmlauncher#1]
Where?

**Comment by AlexMorgan3817** [comment]
Solution: Add interaction in launcher which allow to choose path.
Another solution: Alert user where redactor is installing.

**Comment by SpaiR** [comment]
sdmmlauncher has been deprecated. 
Info where the editor stores data can be found in the readme FAQ: https://github.com/SpaiR/StrongDMM
